# -*- coding: utf-8 -*-
"""Spam Email Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zEeITvUkvPCNrwcNfi_YEU58yH_Mx4fC
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv('emails.csv')

df.head()

print(df.columns)

df.info()

df.head(10)

print(df.shape)

print(df.isnull().sum())

X = df['text']
y = df['spam']

vectorizer = TfidfVectorizer(stop_words='english')

X = vectorizer.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = MultinomialNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy =", accuracy*100,"%")

print(classification_report(y_test, y_pred))

email = [
    "Congratulations! You have won a free iPhone. Click here to claim your prize."
]

email_vector = vectorizer.transform(email)

prediction = model.predict(email_vector)

if prediction[0] == 1:
    print("SPAM EMAIL")
else:
    print("NOT SPAM EMAIL")

import matplotlib.pyplot as plt

df['spam'].value_counts().plot(kind='bar')

plt.title("Spam vs Non-Spam Emails")
plt.xlabel("0 = Not Spam, 1 = Spam")
plt.ylabel("Count")

plt.show()

import pickle

pickle.dump(model, open("spam_model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

print("Model Saved Successfully")

